import { z, ZodRawShape } from "zod"
import { schema } from "../../src/schema/form.schema"
import { TableType } from "./table.object"

export interface AssociationTableProps {

    label:string,
    value:string | boolean

}

export type QueryType = "create" |"select" | "update" | "delete";


export type BookAssociationProps = Record<'autores'|'categorias'|'generos'|'editoras',AssociationTableProps>

export interface InputProps {
    id:string,
    forForm:{
        post:boolean,
        put:boolean
    }
    tag:'input' | 'textarea' | 'select',
    title:string,
    type?:"text" | "number" | "file" | "checkbox" | "email" | "hidden" | "date"
    options?:{
        isMultiple:boolean,
        list:AssociationTableProps[]
        hasQuery:boolean
    }
    numberLimit?:{
        min:number,
        max:number
    }
    maskFormat?:string,
    numericFormat?:{
        prefix?:string,
        suffix?:string,
        decimalScale?:number
        decimalSeparator?:string,
        thousandSeparator?:string
    },
    registerId:string
    value?:string | number
}


export interface FormListProps {
    name:Exclude<TableType,"none">,
    schema:Record<'post'|'put',z.ZodObject<ZodRawShape>>
    fields:InputProps[],
    // getQueryFields(type:"post"|"put"):Partial<InputProps[]>
}


export interface FormObjectProps {
    formList:FormListProps[]
}

// const onGetQueryFields = (
//     queryType:"post" | "put",fields:{
//         post?:Partial<InputProps[]>,
//         put?:Partial<InputProps[]>
//     })=>{
//     return queryType == "post"
//     ? fields.post
//     : queryType == "put"
//     ? fields.put
//     : []
// }



const form:FormObjectProps = {
    formList:[
        {
            name:"user",
            schema:{
                post:schema.schemaList['user'].register.step1
            .merge(schema.schemaList['user'].register.step2)
            .merge(schema.schemaList['user'].register.step3 as any) as z.ZodObject<ZodRawShape>,
            put:schema.schemaList['user'].register.step1
            .merge(schema.schemaList['user'].register.step2)
            },
            fields:[
                {
                    id:"nome_id",
                     forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Nome",
                    type:"text",
                    registerId:"nome"
                },
                {
                    id:"sobrenome_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Sobrenome",
                    type:"text",
                    registerId:"sobrenome"
                },
                {
                    id:"cpf_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"CPF",
                    type:"text",
                    registerId:"cpf",
                    maskFormat:"###.###.###-##"
                },
                {
                    id:"username_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Username",
                    type:"text",
                    registerId:"username",
                },
                {
                    id:"email_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Email",
                    type:"email",
                    registerId:"email",
                }
            ]
        },
        {
            name:"library_user",
            schema:{
                post:schema.schemaList['library_user'].omit({
                    situacao:true
                }),
                put:schema.schemaList['library_user'].omit({
                    usuarios:true,
                    cpf:true
                })
            },
            fields:[
                {
                    id:"users_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Usuário",
                    registerId:"usuarios"
                },
                {
                    id:"accounts_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Perfil",
                    registerId:"perfis_biblioteca"
                },
                {
                    id:"userType_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:false,
                        list:[
                            {
                                label:"Comum",
                                value:"comum"
                            },
                            {
                                label:"Administrador",
                                value:"admin"
                            }
                        ]
                    },
                    title:"Tipo de usuário",
                    registerId:"tipo_usuario"
                },
                {
                    id:"situation_id",
                    forForm:{
                        post:false,
                        put:true
                    },
                    tag:"select",
                     options:{
                        isMultiple:false,
                        hasQuery:false,
                        list:[{
                            label:"ativo",
                            value:"ativo"
                        },{
                            label:"bloqueado",
                            value:"bloqueado"
                        }]
                    },
                    title:"Situação",
                    registerId:"situacao"
                },
                {
                    id:"matriculationNumber_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Número da matrícula",
                    registerId:"numero_matricula"
                },
                {
                    id:"cpf_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"input",
                    title:"CPF",
                    type:"text",
                    registerId:"cpf",
                    maskFormat:"###.###.###-##"
                }
            ]
        },
        {
            name:"account",
            schema:{
                post:schema.schemaList['account'],
                put:schema.schemaList['account']
            },
            fields:[
                {
                    id:"name_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Nome",
                    registerId:"nome"
                },
                {
                    id:"amerce_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    numericFormat:{
                        prefix:"R$",
                        decimalScale:0,
                        decimalSeparator:",",
                        thousandSeparator:".",
                    },
                    title:"Multa padrão",
                    registerId:"multa_padrao"
                },
                {
                    id:"paybackPeriod_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    numericFormat:{
                        decimalScale:0,
                        suffix:" dias"
                    },
                    title:"Prazo de devolução padrão",
                    registerId:"prazo_devolucao_padrao"
                },
                {
                    id:"amercePeriod_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    numericFormat:{
                        decimalScale:0,
                        suffix:" dias"
                    },
                    title:"Prazo de multa padrão",
                    registerId:"prazo_multa_padrao"
                }
            ]
        },
        {
            name:"book",
            schema:{
                post:schema.schemaList['book'],
                put:schema.schemaList['book']
            },
            fields:[
                {
                    id:"ISBN_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"ISBN",
                    type:'text',
                    maskFormat:"###-#-##-######-#",
                    registerId:"ISBN"
                },
                {
                    id:"image_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Capa",
                    type:"file",
                    registerId:"imagem"
                },
                {
                    id:"title_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Título",
                    type:"text",
                    registerId:"titulo"
                },
                {
                    id:"description_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"textarea",
                    title:"Descrição",
                    type:"text",
                    registerId:"descricao"
                },
                {
                    id:"releaseYear_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    title:"Ano de lançamento",
                    type:"number",
                    numberLimit:{
                        min:1000,
                        max:2100
                    },
                    registerId:"ano_lancamento"
                },
                {
                    id:"authors_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    title:"Autores",
                    registerId:"autores",
                    options:{
                        isMultiple:true,
                        list:[],
                        hasQuery:true
                    }
                },
                {
                    id:"categories_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    title:"Categorias",
                    registerId:"categorias",
                    options:{
                        isMultiple:true,
                        list:[],
                        hasQuery:true
                    }
                },
                {
                    id:"genders_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    title:"Gêneros",
                    registerId:"generos",
                    options:{
                        isMultiple:true,
                        list:[],
                        hasQuery:true
                    }
                },
                {
                    id:"publishers_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    title:"Editoras",
                    registerId:"editoras",
                    options:{
                        isMultiple:true,
                        list:[],
                        hasQuery:true
                    }
                }
            ],
        },{
            name:"author",
            schema:{
                post:schema.schemaList['author'],
                put:schema.schemaList['author']
            },
            fields:[
                {
                    id:"name_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Nome",
                    registerId:"nome"
                }
            ]

        },{
            name:"publisher",
            schema:{
                post:schema.schemaList['publisher'],
                put:schema.schemaList['publisher']
            },
            fields:[
                {
                    id:"name_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Nome",
                    registerId:"nome"
                }
            ]

        },{
            name:"category",
            schema:{
                post:schema.schemaList['category'],
                put:schema.schemaList['category']
            },
            fields:[
                {
                    id:"name_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Nome",
                    registerId:"nome"
                }
            ]

        },{
            name:"gender",
            schema:{
                post:schema.schemaList['gender'],
                put:schema.schemaList['gender']
            },
            fields:[
                {
                    id:"name_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Nome",
                    registerId:"nome"
                }
            ]

        },{
            name:"exemplary",
            schema:{
                post:schema.schemaList['exemplary'],
                put:schema.schemaList['exemplary']
            },
            fields:[
                {
                    id:"bookId_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        list:[],
                        hasQuery:true
                    },
                    title:"Livros",
                    registerId:"livros_biblioteca"
                },
                {
                    id:"tomboNumber_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    title:"Número tombo",
                    registerId:"numero_tombo"
                },
                {
                    id:"situation_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        list:[
                            {
                                value:'disponivel',
                                label:"Disponível"
                            },{
                                value:'indisponivel',
                                label:"Indisponível"
                            },
                        ],
                        hasQuery:false
                    },
                    title:"Situação",
                    registerId:"situacao"
                },
                {
                    id:"sector_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Setor",
                    registerId:"setor"
                },
                {
                    id:"shelf_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Prateleira",
                    registerId:"prateleira"
                },
                {
                    id:"stand_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Estante",
                    registerId:"estante"
                }
            ]
        },
        {
            name:"loan",
            schema:{
                post:schema.schemaList['loan'].omit(
                {
                    data_devolucao:true,
                    situacao:true
                }),
                put:schema.schemaList['loan'].omit(
                    {
                        exemplares_biblioteca:true,
                        usuarios_biblioteca:true
                    }
                )
            },
            fields:[
                {
                    id:"exemplary_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"select",
                    options:{
                        isMultiple:true,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Exemplares",
                    registerId:"exemplares_biblioteca"
                },
                {
                    id:"libraryUser_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Usuário",
                    registerId:"usuarios_biblioteca"
                },
                {
                    id:"situation_id",
                    forForm:{
                        post:false,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:false,
                        list:[
                            {
                                label:"Concluido",
                                value:"concluido"
                            },
                            {
                                label:"Cancelado",
                                value:"cancelado"
                            }
                        ]
                    },
                    title:"Situação",
                    registerId:"situacao"
                },
                {
                    id:"devolutionDate_id",
                    forForm:{
                        post:false,
                        put:true
                    },
                    tag:"input",
                    type:"date",
                    title:"Data de devolução",
                    registerId:"data_devolucao"
                }
            ]
        },
        {
            name:"reserve",
            schema:{
                post:schema.schemaList['reserve']
                .omit({
                    data_retirada:true,
                    situacao:true,
                    exemplares:true
                }),
                put:schema.schemaList['reserve']
                .omit({
                    usuarios_biblioteca:true,
                    livros_biblioteca:true
                })
            },
            fields:[
                {
                    id:"book_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Livros",
                    registerId:"livros_biblioteca"
                },
                {
                    id:"exemplaries_id",
                    forForm:{
                        post:false,
                        put:false
                    },
                    tag:"textarea",
                    title:"Exemplares",
                    registerId:"exemplares"
                },
                {
                    id:"book_quantity_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    title:"Quantidade",
                    registerId:"quantidade_total"
                },
                {
                    id:"libraryUser_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Usuário",
                    registerId:"usuarios_biblioteca"
                },
                {
                    id:"situation_id",
                    forForm:{
                        post:false,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:false,
                        list:[
                            {
                                label:"Concluido",
                                value:"concluido"
                            },
                            {
                                label:"Cancelado",
                                value:"cancelado"
                            }
                        ]
                    },
                    title:"Situação",
                    registerId:"situacao"
                },
                {
                    id:"withdrawalDate_id",
                    tag:"input",
                    type:"date",
                    title:"Data de retirada",
                    registerId:"data_retirada",
                    forForm:{
                        post:false,
                        put:true
                    },
                }
            ]
        },{
            name:"amerce",
            schema:{
                post:schema.schemaList['amerce'].omit({
                    valor:true
                }),
                put:schema.schemaList['amerce'].omit({
                    usuarios_biblioteca:true,
                    valor:true
                })
            },
            fields:[
                {
                    id:"libraryUser_id",
                    forForm:{
                        post:true,
                        put:false
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:true,
                        list:[]
                    },
                    title:"Aplicar para usuário",
                    registerId:"usuarios_biblioteca"
                },
                {
                    id:"value_id",
                    forForm:{
                        post:false,
                        put:false
                    },
                    tag:"input",
                    type:"number",
                    numericFormat:{
                        prefix:"R$",
                        decimalScale:0,
                        decimalSeparator:",",
                        thousandSeparator:".",
                    },
                    title:"Valor",
                    registerId:"valor",
                },
                {
                    id:"motive_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"textarea",
                    title:"Motivo",
                    registerId:"motivo"
                },
                {
                    id:"situation_id",
                    forForm:{
                        post:false,
                        put:true
                    },
                    tag:"select",
                    options:{
                        isMultiple:false,
                        hasQuery:false,
                        list:[
                            {
                                label:"Concluido",
                                value:"concluido"
                            },
                            {
                                label:"Cancelado",
                                value:"cancelado"
                            }
                        ]
                    },
                    title:"Situação",
                    registerId:"situacao"
                }
            ]
        },{
            name:"library",
            schema:{
                post:schema.schemaList['library'],
                put:schema.schemaList['library']
            },
            fields:[
                {
                    id:"name_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Nome",
                    registerId:"nome"
                },
                {
                    id:"telephone_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    maskFormat:"(11) ####-####",
                    title:"Telefone",
                    registerId:"telefone"
                },
                {
                    id:"roadAdress_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"text",
                    title:"Rua",
                    registerId:"rua"
                },
                {
                    id:"numberAdress_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    title:"Número",
                    registerId:"numero"
                },
                {
                    id:"cepAdress_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"input",
                    type:"number",
                    maskFormat:"#####-###",
                    title:"Cep",
                    registerId:"cep"
                },
                {
                    id:"reserveOption_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        hasQuery:false,
                        isMultiple:false,
                        list:[
                            {
                                value:true,
                                label:"Habilitar"
                            },
                            {
                                value:false,
                                label:"Desabilitar"
                            }
                        ]
                    },
                    title:"Reservas online",
                    registerId:"reserva_online"
                },
                {
                    id:"amerceOption_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        hasQuery:false,
                        isMultiple:false,
                        list:[
                            {
                                value:true,
                                label:"Habilitar"
                            },
                            {
                                value:false,
                                label:"Desabilitar"
                            }
                        ]
                    },
                    title:"Multa para devoluções vencidas",
                    registerId:"aplicacao_multa"
                },
                {
                    id:"userBlockOption_id",
                    forForm:{
                        post:true,
                        put:true
                    },
                    tag:"select",
                    options:{
                        hasQuery:false,
                        isMultiple:false,
                        list:[
                            {
                                value:true,
                                label:"Habilitar"
                            },
                            {
                                value:false,
                                label:"Desabilitar"
                            }
                        ]
                    },
                    title:"Bloqueio de conta para devoluções vencidas",
                    registerId:"aplicacao_bloqueio"
                }
            ]
        }

    ]
}



export {
    form
}
